version: 1.0.{build}
build:
  project: src\FastSmsSdk.sln
  publish_nuget: true
  publish_nuget_symbols: true
  include_nuget_references: true
  verbosity: minimal
after_build:
- nuget pack src\FastSmsSdk\*.csproj  -Version "%APPVEYOR_BUILD_VERSION%"

test:
  categories:
    only:
    - Unit

artifacts:
- path: '*.nupkg'
  name: FastSmsSdk
install:
  - nuget restore src\FastSmsSdk.sln
  - nuget install Moq -Version 4.1.1309.1617 -OutputDirectory tests\FastSmsSdk.Tests

deploy:
  provider: NuGet
  api_key: 1b24e802-22f1-422c-8ce4-86379fb700ea
  artifact: FastSmsSdk
  on:
    branch: master
  
  
