//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FastSmsSdk.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FastSmsSdk.Localization.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Source Address – Alphanumeric too long.
        /// </summary>
        internal static string AlphanumericTooLong {
            get {
                return ResourceManager.GetString("AlphanumericTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blank Body.
        /// </summary>
        internal static string BlankBody {
            get {
                return ResourceManager.GetString("BlankBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BlankMessageBody.
        /// </summary>
        internal static string BlankMessageBody {
            get {
                return ResourceManager.GetString("BlankMessageBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blank or Invalid Source Address.
        /// </summary>
        internal static string BlankOrInvalidSourceAddress {
            get {
                return ResourceManager.GetString("BlankOrInvalidSourceAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distribution List is Empty.
        /// </summary>
        internal static string DistributionListIsEmpty {
            get {
                return ResourceManager.GetString("DistributionListIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Creating User.
        /// </summary>
        internal static string ErrorCreatingUser {
            get {
                return ResourceManager.GetString("ErrorCreatingUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General Database Error.
        /// </summary>
        internal static string GeneralDatabaseError {
            get {
                return ResourceManager.GetString("GeneralDatabaseError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group is Empty.
        /// </summary>
        internal static string GroupIsEmpty {
            get {
                return ResourceManager.GetString("GroupIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Amount Specified.
        /// </summary>
        internal static string InvalidAmountSpecified {
            get {
                return ResourceManager.GetString("InvalidAmountSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Contact.
        /// </summary>
        internal static string InvalidContact {
            get {
                return ResourceManager.GetString("InvalidContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid CreditID.
        /// </summary>
        internal static string InvalidCreditId {
            get {
                return ResourceManager.GetString("InvalidCreditId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Currency Requested.
        /// </summary>
        internal static string InvalidCurrencyRequested {
            get {
                return ResourceManager.GetString("InvalidCurrencyRequested", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Destination Address.
        /// </summary>
        internal static string InvalidDestinationAddress {
            get {
                return ResourceManager.GetString("InvalidDestinationAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Distribution List.
        /// </summary>
        internal static string InvalidDistributionList {
            get {
                return ResourceManager.GetString("InvalidDistributionList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid From Timestamp.
        /// </summary>
        internal static string InvalidFromTimestamp {
            get {
                return ResourceManager.GetString("InvalidFromTimestamp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Group.
        /// </summary>
        internal static string InvalidGroup {
            get {
                return ResourceManager.GetString("InvalidGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid/Missing Details.
        /// </summary>
        internal static string InvalidMissingDetails {
            get {
                return ResourceManager.GetString("InvalidMissingDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Source Address – Invalid Number.
        /// </summary>
        internal static string InvalidNumber {
            get {
                return ResourceManager.GetString("InvalidNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Schedule Date.
        /// </summary>
        internal static string InvalidScheduleDate {
            get {
                return ResourceManager.GetString("InvalidScheduleDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid To Timestamp.
        /// </summary>
        internal static string InvalidToTimestamp {
            get {
                return ResourceManager.GetString("InvalidToTimestamp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Validity Period.
        /// </summary>
        internal static string InvalidValidityPeriod {
            get {
                return ResourceManager.GetString("InvalidValidityPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The system is down for maintenance.
        /// </summary>
        internal static string IsDownForMaintenance {
            get {
                return ResourceManager.GetString("IsDownForMaintenance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License expired.
        /// </summary>
        internal static string LicenseExpired {
            get {
                return ResourceManager.GetString("LicenseExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License in use.
        /// </summary>
        internal static string LicenseInUse {
            get {
                return ResourceManager.GetString("LicenseInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No License available.
        /// </summary>
        internal static string NoLicenseAvailable {
            get {
                return ResourceManager.GetString("NoLicenseAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Route Available.
        /// </summary>
        internal static string NoRouteAvailable {
            get {
                return ResourceManager.GetString("NoRouteAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Enough Credits.
        /// </summary>
        internal static string NotEnoughCredits {
            get {
                return ResourceManager.GetString("NotEnoughCredits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NoUserIDSpecified.
        /// </summary>
        internal static string NoUserIDSpecified {
            get {
                return ResourceManager.GetString("NoUserIDSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number is blacklisted.
        /// </summary>
        internal static string NumberIsBlacklisted {
            get {
                return ResourceManager.GetString("NumberIsBlacklisted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Received XML Error.
        /// </summary>
        internal static string ReceivedXmlError {
            get {
                return ResourceManager.GetString("ReceivedXmlError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return XML Error.
        /// </summary>
        internal static string ReturnXmlError {
            get {
                return ResourceManager.GetString("ReturnXmlError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have exceeded the limit of messages you can send in a single day to a single number.
        /// </summary>
        internal static string SingleNumber {
            get {
                return ResourceManager.GetString("SingleNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some numbers in list failed.
        /// </summary>
        internal static string SomeNumbersInListFailed {
            get {
                return ResourceManager.GetString("SomeNumbersInListFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source Address Not Allowed (Email2SMS).
        /// </summary>
        internal static string SourceAddressNotAllowed {
            get {
                return ResourceManager.GetString("SourceAddressNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to create List.
        /// </summary>
        internal static string UnableToCreateList {
            get {
                return ResourceManager.GetString("UnableToCreateList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown Action.
        /// </summary>
        internal static string UnknownAction {
            get {
                return ResourceManager.GetString("UnknownAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown Error.
        /// </summary>
        internal static string UnknownError {
            get {
                return ResourceManager.GetString("UnknownError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown Group.
        /// </summary>
        internal static string UnknownGroup {
            get {
                return ResourceManager.GetString("UnknownGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown/Invalid User.
        /// </summary>
        internal static string UnknownInvalidUser {
            get {
                return ResourceManager.GetString("UnknownInvalidUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown List.
        /// </summary>
        internal static string UnknownList {
            get {
                return ResourceManager.GetString("UnknownList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown Message ID.
        /// </summary>
        internal static string UnknownMessageID {
            get {
                return ResourceManager.GetString("UnknownMessageID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown Report Type.
        /// </summary>
        internal static string UnknownReportType {
            get {
                return ResourceManager.GetString("UnknownReportType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown Username/Password.
        /// </summary>
        internal static string UnknownUsernamePassword {
            get {
                return ResourceManager.GetString("UnknownUsernamePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot set a user’s credits to be less than 0.
        /// </summary>
        internal static string UsersCredits {
            get {
                return ResourceManager.GetString("UsersCredits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Suspended.
        /// </summary>
        internal static string UserSuspended {
            get {
                return ResourceManager.GetString("UserSuspended", resourceCulture);
            }
        }
    }
}
